<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Laravel's own standard database-notification storage, generated by
 * `php artisan notifications:table` and left in its default shape - not a custom table.
 *
 * `User` already carries the `Notifiable` trait (added when the project's own password-reset
 * and email-verification notifications were built) and `notifiable()` is already a real,
 * morphable relationship; this table is the one piece that was missing to let a notification
 * actually persist and be read back through the API, rather than only being deliverable
 * through the `mail` channel the way `VerifyEmail`/`ResetPassword` already are.
 *
 * `notifiable_type`/`notifiable_id` are polymorphic on purpose, even though every notification
 * class this module ships targets `User` today: it is the identical, zero-cost-now
 * extensibility Laravel's own architecture already provides, not a custom generalisation this
 * project invented. `type` is the notification class's own FQCN, `data` is that class's
 * `toArray()` payload, and `read_at` is the whole read/unread mechanism - null is unread, a
 * timestamp is read, exactly the reliable state/timestamp pair this module's own read
 * endpoints rely on.
 */
return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('notifications', function (Blueprint $table) {
            $table->uuid('id')->primary();
            $table->string('type');
            $table->morphs('notifiable');
            $table->text('data');
            $table->timestamp('read_at')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('notifications');
    }
};
